-- Neutralizada (2026-09-24): `temporada_sin_salida` y el aviso público "No
-- hubo salida (COVID)" se han eliminado por decisión del usuario. Este fichero
-- se deja vacío en vez de borrarlo: migrate_ingest.php re-ejecuta todos los
-- .sql de este directorio en orden alfabético en cada despliegue, así que si
-- 014 desapareciera el hueco numérico no importaría, pero dejarlo vacío deja
-- constancia de que existió y evita reutilizar el número 014 por error. La
-- tabla se borra en 018_drop_temporada_sin_salida.sql (tiene que ir en un
-- fichero posterior en orden alfabético para no resucitarla en el mismo host
-- que todavía la tenga creada de una migración anterior).
